
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\004\000\002\015\007\000\002\015" +
    "\005\000\002\007\010\000\002\007\010\000\002\007\010" +
    "\000\002\007\002\000\002\012\003\000\002\010\005\000" +
    "\002\010\003\000\002\010\002\000\002\011\004\000\002" +
    "\011\002\000\002\013\007\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\003\000\002\005\004" +
    "\000\002\005\003\000\002\003\005\000\002\003\005\000" +
    "\002\003\005\000\002\003\007\000\002\003\012\000\002" +
    "\003\007\000\002\003\007\000\002\003\005\000\002\006" +
    "\004\000\002\006\003\000\002\004\005\000\002\004\006" +
    "\000\002\004\004\000\002\004\005\000\002\004\005\000" +
    "\002\004\005\000\002\004\005\000\002\004\004\000\002" +
    "\004\004\000\002\004\004\000\002\004\004\000\002\004" +
    "\005\000\002\004\004\000\002\004\006\000\002\004\005" +
    "\000\002\002\005\000\002\002\005\000\002\002\005\000" +
    "\002\002\005\000\002\002\005\000\002\002\005\000\002" +
    "\002\004\000\002\002\003\000\002\002\003\000\002\002" +
    "\005\000\002\002\005\000\002\002\004\000\002\002\003" +
    "\000\002\002\003\000\002\002\005\000\002\002\005\000" +
    "\002\002\005\000\002\002\005\000\002\002\005\000\002" +
    "\002\005\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\224\000\006\004\005\005\004\001\002\000\020\004" +
    "\152\005\150\011\154\012\151\057\153\060\157\061\147" +
    "\001\002\000\012\005\ufffb\007\ufffb\040\ufffb\052\ufffb\001" +
    "\002\000\004\002\007\001\002\000\004\002\001\001\002" +
    "\000\012\005\013\007\012\040\011\052\014\001\002\000" +
    "\004\010\221\001\002\000\004\010\215\001\002\000\020" +
    "\004\152\005\150\011\154\012\151\057\153\060\157\061" +
    "\147\001\002\000\004\010\015\001\002\000\004\066\016" +
    "\001\002\000\012\006\ufffa\023\ufffa\024\ufffa\037\ufffa\001" +
    "\002\000\006\006\ufff5\037\ufff5\001\002\000\006\006\022" +
    "\037\023\001\002\000\006\006\ufff6\037\ufff6\001\002\000" +
    "\012\005\ufffe\007\ufffe\040\ufffe\052\ufffe\001\002\000\030" +
    "\015\031\021\034\031\025\051\026\056\033\062\040\063" +
    "\032\066\036\067\027\070\030\071\024\001\002\000\042" +
    "\014\uffc7\015\uffc7\016\uffc7\017\uffc7\020\uffc7\022\uffc7\023" +
    "\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7\032\uffc7\033\uffc7" +
    "\042\uffc7\043\uffc7\044\uffc7\001\002\000\022\015\031\021" +
    "\034\031\025\051\026\066\036\067\027\070\030\071\024" +
    "\001\002\000\042\014\uffc0\015\uffc0\016\uffc0\017\uffc0\020" +
    "\uffc0\022\uffc0\023\uffc0\025\uffc0\026\uffc0\027\uffc0\030\uffc0" +
    "\032\uffc0\033\uffc0\042\uffc0\043\uffc0\044\uffc0\001\002\000" +
    "\042\014\uffcd\015\uffcd\016\uffcd\017\uffcd\020\uffcd\022\uffcd" +
    "\023\uffcd\025\uffcd\026\uffcd\027\uffcd\030\uffcd\032\uffcd\033" +
    "\uffcd\042\uffcd\043\uffcd\044\uffcd\001\002\000\042\014\uffc8" +
    "\015\uffc8\016\uffc8\017\uffc8\020\uffc8\022\uffc8\023\uffc8\025" +
    "\uffc8\026\uffc8\027\uffc8\030\uffc8\032\uffc8\033\uffc8\042\uffc8" +
    "\043\uffc8\044\uffc8\001\002\000\022\015\031\021\034\031" +
    "\025\051\026\066\036\067\027\070\030\071\024\001\002" +
    "\000\004\025\ufff1\001\002\000\004\025\ufff0\001\002\000" +
    "\022\015\031\021\034\031\025\051\026\066\036\067\027" +
    "\070\030\071\024\001\002\000\004\025\073\001\002\000" +
    "\042\014\uffcc\015\uffcc\016\uffcc\017\uffcc\020\uffcc\022\uffcc" +
    "\023\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\032\uffcc\033" +
    "\uffcc\042\uffcc\043\uffcc\044\uffcc\001\002\000\036\014\041" +
    "\015\046\016\044\017\054\020\047\025\ufff3\026\045\027" +
    "\053\030\042\032\050\033\051\042\052\043\043\044\055" +
    "\001\002\000\004\025\ufff2\001\002\000\022\015\031\021" +
    "\034\031\025\051\026\066\036\067\027\070\030\071\024" +
    "\001\002\000\022\015\031\021\034\031\025\051\026\066" +
    "\036\067\027\070\030\071\024\001\002\000\022\015\031" +
    "\021\034\031\025\051\026\066\036\067\027\070\030\071" +
    "\024\001\002\000\022\015\031\021\034\031\025\051\026" +
    "\066\036\067\027\070\030\071\024\001\002\000\022\015" +
    "\031\021\034\031\025\051\026\066\036\067\027\070\030" +
    "\071\024\001\002\000\022\015\031\021\034\031\025\051" +
    "\026\066\036\067\027\070\030\071\024\001\002\000\022" +
    "\015\031\021\034\031\025\051\026\066\036\067\027\070" +
    "\030\071\024\001\002\000\022\015\031\021\034\031\025" +
    "\051\026\066\036\067\027\070\030\071\024\001\002\000" +
    "\022\015\031\021\034\031\025\051\026\066\036\067\027" +
    "\070\030\071\024\001\002\000\022\015\031\021\034\031" +
    "\025\051\026\066\036\067\027\070\030\071\024\001\002" +
    "\000\022\015\031\021\034\031\025\051\026\066\036\067" +
    "\027\070\030\071\024\001\002\000\022\015\031\021\034" +
    "\031\025\051\026\066\036\067\027\070\030\071\024\001" +
    "\002\000\022\015\031\021\034\031\025\051\026\066\036" +
    "\067\027\070\030\071\024\001\002\000\026\014\041\015" +
    "\046\016\044\017\054\020\047\022\uffc1\023\uffc1\025\uffc1" +
    "\032\uffc1\033\uffc1\001\002\000\042\014\uffd1\015\uffd1\016" +
    "\uffd1\017\uffd1\020\uffd1\022\uffd1\023\uffd1\025\uffd1\026\uffd1" +
    "\027\uffd1\030\uffd1\032\uffd1\033\uffd1\042\uffd1\043\uffd1\044" +
    "\uffd1\001\002\000\026\014\041\015\046\016\044\017\054" +
    "\020\047\022\uffc3\023\uffc3\025\uffc3\032\uffc3\033\uffc3\001" +
    "\002\000\026\014\041\015\046\016\044\017\054\020\047" +
    "\022\uffc6\023\uffc6\025\uffc6\032\uffc6\033\uffc6\001\002\000" +
    "\042\014\041\015\046\016\044\017\054\020\047\022\uffcb" +
    "\023\uffcb\025\uffcb\026\045\027\053\030\042\032\uffcb\033" +
    "\uffcb\042\052\043\043\044\055\001\002\000\042\014\041" +
    "\015\046\016\044\017\054\020\047\022\uffca\023\uffca\025" +
    "\uffca\026\045\027\053\030\042\032\uffca\033\051\042\052" +
    "\043\043\044\055\001\002\000\042\014\uffd0\015\uffd0\016" +
    "\uffd0\017\uffd0\020\uffd0\022\uffd0\023\uffd0\025\uffd0\026\uffd0" +
    "\027\uffd0\030\uffd0\032\uffd0\033\uffd0\042\uffd0\043\uffd0\044" +
    "\uffd0\001\002\000\042\014\uffd3\015\uffd3\016\044\017\054" +
    "\020\047\022\uffd3\023\uffd3\025\uffd3\026\uffd3\027\uffd3\030" +
    "\uffd3\032\uffd3\033\uffd3\042\uffd3\043\uffd3\044\uffd3\001\002" +
    "\000\026\014\041\015\046\016\044\017\054\020\047\022" +
    "\uffc5\023\uffc5\025\uffc5\032\uffc5\033\uffc5\001\002\000\042" +
    "\014\uffd2\015\uffd2\016\uffd2\017\uffd2\020\uffd2\022\uffd2\023" +
    "\uffd2\025\uffd2\026\uffd2\027\uffd2\030\uffd2\032\uffd2\033\uffd2" +
    "\042\uffd2\043\uffd2\044\uffd2\001\002\000\026\014\041\015" +
    "\046\016\044\017\054\020\047\022\uffc2\023\uffc2\025\uffc2" +
    "\032\uffc2\033\uffc2\001\002\000\026\014\041\015\046\016" +
    "\044\017\054\020\047\022\uffc4\023\uffc4\025\uffc4\032\uffc4" +
    "\033\uffc4\001\002\000\042\014\uffd4\015\uffd4\016\044\017" +
    "\054\020\047\022\uffd4\023\uffd4\025\uffd4\026\uffd4\027\uffd4" +
    "\030\uffd4\032\uffd4\033\uffd4\042\uffd4\043\uffd4\044\uffd4\001" +
    "\002\000\024\035\105\041\106\045\075\046\104\047\076" +
    "\050\100\053\077\054\074\055\102\001\002\000\022\015" +
    "\031\021\034\031\025\051\026\066\036\067\027\070\030" +
    "\071\024\001\002\000\022\015\031\021\034\031\025\051" +
    "\026\066\036\067\027\070\030\071\024\001\002\000\024" +
    "\015\031\021\034\023\134\031\025\051\026\066\036\067" +
    "\027\070\030\071\024\001\002\000\024\015\031\021\034" +
    "\023\131\031\025\051\026\066\036\067\027\070\030\071" +
    "\024\001\002\000\022\015\031\021\034\031\025\051\026" +
    "\066\036\067\027\070\030\071\024\001\002\000\026\006" +
    "\125\035\105\041\106\045\075\046\104\047\076\050\100" +
    "\053\077\054\074\055\102\001\002\000\006\023\122\034" +
    "\121\001\002\000\026\006\uffe4\035\uffe4\041\uffe4\045\uffe4" +
    "\046\uffe4\047\uffe4\050\uffe4\053\uffe4\054\uffe4\055\uffe4\001" +
    "\002\000\024\015\031\021\034\023\116\031\025\051\026" +
    "\066\036\067\027\070\030\071\024\001\002\000\024\015" +
    "\031\021\034\023\113\031\025\051\026\066\036\067\027" +
    "\070\030\071\024\001\002\000\006\023\110\034\107\001" +
    "\002\000\004\066\111\001\002\000\026\006\uffd7\035\uffd7" +
    "\041\uffd7\045\uffd7\046\uffd7\047\uffd7\050\uffd7\053\uffd7\054" +
    "\uffd7\055\uffd7\001\002\000\004\023\112\001\002\000\026" +
    "\006\uffd6\035\uffd6\041\uffd6\045\uffd6\046\uffd6\047\uffd6\050" +
    "\uffd6\053\uffd6\054\uffd6\055\uffd6\001\002\000\026\006\uffd9" +
    "\035\uffd9\041\uffd9\045\uffd9\046\uffd9\047\uffd9\050\uffd9\053" +
    "\uffd9\054\uffd9\055\uffd9\001\002\000\036\014\041\015\046" +
    "\016\044\017\054\020\047\023\115\026\045\027\053\030" +
    "\042\032\050\033\051\042\052\043\043\044\055\001\002" +
    "\000\026\006\uffdd\035\uffdd\041\uffdd\045\uffdd\046\uffdd\047" +
    "\uffdd\050\uffdd\053\uffdd\054\uffdd\055\uffdd\001\002\000\026" +
    "\006\uffdc\035\uffdc\041\uffdc\045\uffdc\046\uffdc\047\uffdc\050" +
    "\uffdc\053\uffdc\054\uffdc\055\uffdc\001\002\000\036\014\041" +
    "\015\046\016\044\017\054\020\047\023\120\026\045\027" +
    "\053\030\042\032\050\033\051\042\052\043\043\044\055" +
    "\001\002\000\026\006\uffd8\035\uffd8\041\uffd8\045\uffd8\046" +
    "\uffd8\047\uffd8\050\uffd8\053\uffd8\054\uffd8\055\uffd8\001\002" +
    "\000\004\066\123\001\002\000\026\006\uffe1\035\uffe1\041" +
    "\uffe1\045\uffe1\046\uffe1\047\uffe1\050\uffe1\053\uffe1\054\uffe1" +
    "\055\uffe1\001\002\000\004\023\124\001\002\000\026\006" +
    "\uffe2\035\uffe2\041\uffe2\045\uffe2\046\uffe2\047\uffe2\050\uffe2" +
    "\053\uffe2\054\uffe2\055\uffe2\001\002\000\006\006\ufff4\037" +
    "\ufff4\001\002\000\026\006\uffe5\035\uffe5\041\uffe5\045\uffe5" +
    "\046\uffe5\047\uffe5\050\uffe5\053\uffe5\054\uffe5\055\uffe5\001" +
    "\002\000\036\014\041\015\046\016\044\017\054\020\047" +
    "\023\130\026\045\027\053\030\042\032\050\033\051\042" +
    "\052\043\043\044\055\001\002\000\026\006\uffd5\035\uffd5" +
    "\041\uffd5\045\uffd5\046\uffd5\047\uffd5\050\uffd5\053\uffd5\054" +
    "\uffd5\055\uffd5\001\002\000\026\006\uffda\035\uffda\041\uffda" +
    "\045\uffda\046\uffda\047\uffda\050\uffda\053\uffda\054\uffda\055" +
    "\uffda\001\002\000\036\014\041\015\046\016\044\017\054" +
    "\020\047\023\133\026\045\027\053\030\042\032\050\033" +
    "\051\042\052\043\043\044\055\001\002\000\026\006\uffde" +
    "\035\uffde\041\uffde\045\uffde\046\uffde\047\uffde\050\uffde\053" +
    "\uffde\054\uffde\055\uffde\001\002\000\026\006\uffdb\035\uffdb" +
    "\041\uffdb\045\uffdb\046\uffdb\047\uffdb\050\uffdb\053\uffdb\054" +
    "\uffdb\055\uffdb\001\002\000\036\014\041\015\046\016\044" +
    "\017\054\020\047\023\136\026\045\027\053\030\042\032" +
    "\050\033\051\042\052\043\043\044\055\001\002\000\026" +
    "\006\uffdf\035\uffdf\041\uffdf\045\uffdf\046\uffdf\047\uffdf\050" +
    "\uffdf\053\uffdf\054\uffdf\055\uffdf\001\002\000\036\014\041" +
    "\015\046\016\044\017\054\020\047\023\140\026\045\027" +
    "\053\030\042\032\050\033\051\042\052\043\043\044\055" +
    "\001\002\000\026\006\uffe0\035\uffe0\041\uffe0\045\uffe0\046" +
    "\uffe0\047\uffe0\050\uffe0\053\uffe0\054\uffe0\055\uffe0\001\002" +
    "\000\036\014\041\015\046\016\044\017\054\020\047\023" +
    "\142\026\045\027\053\030\042\032\050\033\051\042\052" +
    "\043\043\044\055\001\002\000\026\006\uffe3\035\uffe3\041" +
    "\uffe3\045\uffe3\046\uffe3\047\uffe3\050\uffe3\053\uffe3\054\uffe3" +
    "\055\uffe3\001\002\000\036\014\041\015\046\016\044\017" +
    "\054\020\047\022\144\026\045\027\053\030\042\032\050" +
    "\033\051\042\052\043\043\044\055\001\002\000\042\014" +
    "\uffcf\015\uffcf\016\uffcf\017\uffcf\020\uffcf\022\uffcf\023\uffcf" +
    "\025\uffcf\026\uffcf\027\uffcf\030\uffcf\032\uffcf\033\uffcf\042" +
    "\uffcf\043\uffcf\044\uffcf\001\002\000\042\014\uffce\015\uffce" +
    "\016\uffce\017\uffce\020\uffce\022\uffce\023\uffce\025\uffce\026" +
    "\uffce\027\uffce\030\uffce\032\uffce\033\uffce\042\uffce\043\uffce" +
    "\044\uffce\001\002\000\042\014\uffc9\015\uffc9\016\uffc9\017" +
    "\uffc9\020\uffc9\022\uffc9\023\uffc9\025\uffc9\026\uffc9\027\uffc9" +
    "\030\uffc9\032\uffc9\033\uffc9\042\uffc9\043\uffc9\044\uffc9\001" +
    "\002\000\010\023\ufff7\024\ufff7\066\016\001\002\000\020" +
    "\004\152\005\150\011\154\012\151\057\153\060\157\061" +
    "\147\001\002\000\022\015\031\021\034\031\025\051\026" +
    "\066\036\067\027\070\030\071\024\001\002\000\012\005" +
    "\ufffb\007\ufffb\040\ufffb\052\ufffb\001\002\000\010\023\ufff7" +
    "\024\ufff7\066\016\001\002\000\022\015\031\021\034\031" +
    "\025\051\026\066\036\067\027\070\030\071\024\001\002" +
    "\000\022\004\152\005\150\006\165\011\154\012\151\057" +
    "\153\060\157\061\147\001\002\000\024\004\uffee\005\uffee" +
    "\006\uffee\011\uffee\012\uffee\013\uffee\057\uffee\060\uffee\061" +
    "\uffee\001\002\000\010\023\ufff7\024\ufff7\066\016\001\002" +
    "\000\006\023\163\024\162\001\002\000\006\023\ufff8\024" +
    "\ufff8\001\002\000\004\066\016\001\002\000\024\004\uffed" +
    "\005\uffed\006\uffed\011\uffed\012\uffed\013\uffed\057\uffed\060" +
    "\uffed\061\uffed\001\002\000\006\023\ufff9\024\ufff9\001\002" +
    "\000\004\002\000\001\002\000\024\004\uffef\005\uffef\006" +
    "\uffef\011\uffef\012\uffef\013\uffef\057\uffef\060\uffef\061\uffef" +
    "\001\002\000\036\014\041\015\046\016\044\017\054\020" +
    "\047\025\170\026\045\027\053\030\042\032\050\033\051" +
    "\042\052\043\043\044\055\001\002\000\020\004\152\005" +
    "\150\011\154\012\151\057\153\060\157\061\147\001\002" +
    "\000\022\004\152\005\150\006\172\011\154\012\151\057" +
    "\153\060\157\061\147\001\002\000\024\004\uffe8\005\uffe8" +
    "\006\uffe8\011\uffe8\012\uffe8\013\uffe8\057\uffe8\060\uffe8\061" +
    "\uffe8\001\002\000\006\023\174\024\162\001\002\000\024" +
    "\004\uffec\005\uffec\006\uffec\011\uffec\012\uffec\013\uffec\057" +
    "\uffec\060\uffec\061\uffec\001\002\000\012\005\176\007\012" +
    "\040\011\052\014\001\002\000\020\004\152\005\150\011" +
    "\154\012\151\057\153\060\157\061\147\001\002\000\022" +
    "\004\152\005\150\006\200\011\154\012\151\057\153\060" +
    "\157\061\147\001\002\000\024\004\uffe7\005\uffe7\006\uffe7" +
    "\011\uffe7\012\uffe7\013\uffe7\057\uffe7\060\uffe7\061\uffe7\001" +
    "\002\000\036\014\041\015\046\016\044\017\054\020\047" +
    "\025\202\026\045\027\053\030\042\032\050\033\051\042" +
    "\052\043\043\044\055\001\002\000\020\004\152\005\150" +
    "\011\154\012\151\057\153\060\157\061\147\001\002\000" +
    "\024\004\152\005\150\006\204\011\154\012\151\013\205" +
    "\057\153\060\157\061\147\001\002\000\024\004\uffea\005" +
    "\uffea\006\uffea\011\uffea\012\uffea\013\uffea\057\uffea\060\uffea" +
    "\061\uffea\001\002\000\004\025\206\001\002\000\020\004" +
    "\152\005\150\011\154\012\151\057\153\060\157\061\147" +
    "\001\002\000\022\004\152\005\150\006\210\011\154\012" +
    "\151\057\153\060\157\061\147\001\002\000\024\004\uffe9" +
    "\005\uffe9\006\uffe9\011\uffe9\012\uffe9\013\uffe9\057\uffe9\060" +
    "\uffe9\061\uffe9\001\002\000\022\004\152\005\150\006\212" +
    "\011\154\012\151\057\153\060\157\061\147\001\002\000" +
    "\024\004\uffe6\005\uffe6\006\uffe6\011\uffe6\012\uffe6\013\uffe6" +
    "\057\uffe6\060\uffe6\061\uffe6\001\002\000\006\023\214\024" +
    "\162\001\002\000\024\004\uffeb\005\uffeb\006\uffeb\011\uffeb" +
    "\012\uffeb\013\uffeb\057\uffeb\060\uffeb\061\uffeb\001\002\000" +
    "\004\066\016\001\002\000\006\006\ufff5\037\ufff5\001\002" +
    "\000\006\006\220\037\023\001\002\000\012\005\ufffd\007" +
    "\ufffd\040\ufffd\052\ufffd\001\002\000\004\066\016\001\002" +
    "\000\006\006\ufff5\037\ufff5\001\002\000\006\006\224\037" +
    "\023\001\002\000\012\005\ufffc\007\ufffc\040\ufffc\052\ufffc" +
    "\001\002\000\022\004\152\005\150\006\226\011\154\012" +
    "\151\057\153\060\157\061\147\001\002\000\004\002\uffff" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\224\000\004\015\005\001\001\000\006\003\155\005" +
    "\224\001\001\000\004\007\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\155\005\154\001\001\000\002" +
    "\001\001\000\004\012\016\001\001\000\002\001\001\000" +
    "\004\011\017\001\001\000\004\013\020\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\002\036\014\034\001" +
    "\001\000\002\001\001\000\004\002\145\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\002" +
    "\144\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\002\142\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\071\001\001" +
    "\000\004\002\070\001\001\000\004\002\067\001\001\000" +
    "\004\002\066\001\001\000\004\002\065\001\001\000\004" +
    "\002\064\001\001\000\004\002\063\001\001\000\004\002" +
    "\062\001\001\000\004\002\061\001\001\000\004\002\060" +
    "\001\001\000\004\002\057\001\001\000\004\002\056\001" +
    "\001\000\004\002\055\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\102\006\100" +
    "\001\001\000\004\002\140\001\001\000\004\002\136\001" +
    "\001\000\004\002\134\001\001\000\004\002\131\001\001" +
    "\000\004\002\126\001\001\000\004\004\125\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\116\001\001" +
    "\000\004\002\113\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\212\012" +
    "\160\001\001\000\006\003\155\005\210\001\001\000\004" +
    "\002\200\001\001\000\004\007\174\001\001\000\006\010" +
    "\172\012\160\001\001\000\004\002\166\001\001\000\004" +
    "\003\165\001\001\000\002\001\001\000\006\010\157\012" +
    "\160\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\163\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\155\005\170\001\001\000\004\003\165\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\155\005\176\001\001\000\004\003" +
    "\165\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\155\005\202\001\001\000\004\003\165\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\155\005\206" +
    "\001\001\000\004\003\165\001\001\000\002\001\001\000" +
    "\004\003\165\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\215\001\001\000\004\011" +
    "\216\001\001\000\004\013\020\001\001\000\002\001\001" +
    "\000\004\012\221\001\001\000\004\011\222\001\001\000" +
    "\004\013\020\001\001\000\002\001\001\000\004\003\165" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicial EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		AST start_val = (AST)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicial ::= TkCreate lista_declr TkExecute secuenciacontr TkEnd 
            {
              AST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ArrayList<Declaracion> d = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Programa(d, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicial",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicial ::= TkExecute secuenciacontr TkEnd 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Programa(null, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicial",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_declr ::= lista_declr TkBool TkBot ident lista_comp TkEnd 
            {
              ArrayList<Declaracion> RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		ArrayList<Declaracion> ld = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Identificador id = (Identificador)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Comportamiento> c = (ArrayList<Comportamiento>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 ld.add(new Declaracion("bool", id, c)); RESULT = ld; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_declr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_declr ::= lista_declr TkInt TkBot ident lista_comp TkEnd 
            {
              ArrayList<Declaracion> RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		ArrayList<Declaracion> ld = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Identificador id = (Identificador)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Comportamiento> c = (ArrayList<Comportamiento>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 ld.add(new Declaracion("int", id, c)); RESULT = ld; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_declr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_declr ::= lista_declr TkChar TkBot ident lista_comp TkEnd 
            {
              ArrayList<Declaracion> RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		ArrayList<Declaracion> ld = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Identificador id = (Identificador)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Comportamiento> c = (ArrayList<Comportamiento>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 ld.add(new Declaracion("char", id, c)); RESULT = ld; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_declr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_declr ::= 
            {
              ArrayList<Declaracion> RESULT =null;
		 RESULT = new ArrayList<Declaracion>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_declr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ident ::= TkIdent 
            {
              Identificador RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Identificador(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ident",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_ident ::= lista_ident TkComa ident 
            {
              ArrayList<Identificador> RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<Identificador> li = (ArrayList<Identificador>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Identificador i = (Identificador)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 li.add(i); RESULT = li; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ident",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_ident ::= ident 
            {
              ArrayList<Identificador> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Identificador i = (Identificador)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ArrayList<Identificador> lista = new ArrayList<Identificador>(); lista.add(i); RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ident",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_ident ::= 
            {
              ArrayList<Identificador> RESULT =null;
		 RESULT = new ArrayList<Identificador>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ident",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_comp ::= lista_comp comportamiento 
            {
              ArrayList<Comportamiento> RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Comportamiento> lc = (ArrayList<Comportamiento>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Comportamiento c = (Comportamiento)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 lc.add(c); RESULT = lc; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_comp",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_comp ::= 
            {
              ArrayList<Comportamiento> RESULT =null;
		 RESULT = new ArrayList<Comportamiento>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_comp",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // comportamiento ::= TkOn condicion TkDosPuntos secuenciarobot TkEnd 
            {
              Comportamiento RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Comportamiento(c, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comportamiento",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // condicion ::= expr 
            {
              Condicion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new CondExpresion(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // condicion ::= TkActivation 
            {
              Condicion RESULT =null;
		 RESULT = new CondActivation(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // condicion ::= TkDeactivation 
            {
              Condicion RESULT =null;
		 RESULT = new CondDeactivation(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // condicion ::= TkDefault 
            {
              Condicion RESULT =null;
		 RESULT = new CondDefault(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // secuenciacontr ::= secuenciacontr instcontr 
            {
              Instruccion RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Secuenciacion(s, i); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("secuenciacontr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // secuenciacontr ::= instcontr 
            {
              Instruccion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("secuenciacontr",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // instcontr ::= TkActivate lista_ident TkPunto 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Identificador> id = (ArrayList<Identificador>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Activacion(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // instcontr ::= TkAdvance lista_ident TkPunto 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Identificador> id = (ArrayList<Identificador>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Avance(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // instcontr ::= TkDeactivate lista_ident TkPunto 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Identificador> id = (ArrayList<Identificador>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Desactivacion(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // instcontr ::= TkIf expr TkDosPuntos secuenciacontr TkEnd 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Condicional(e, s, null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // instcontr ::= TkIf expr TkDosPuntos secuenciacontr TkElse TkDosPuntos secuenciacontr TkEnd 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Instruccion s1 = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s2 = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Condicional(e, s1, s2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // instcontr ::= TkWhile expr TkDosPuntos secuenciacontr TkEnd 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new IteracionIndet(e, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // instcontr ::= TkCreate lista_declr TkExecute secuenciacontr TkEnd 
            {
              Instruccion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ArrayList<Declaracion> d = (ArrayList<Declaracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new IncorpAlcance(d, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // instcontr ::= TkExecute secuenciacontr TkEnd 
            {
              Instruccion RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new IncorpAlcance(null, s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instcontr",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // secuenciarobot ::= secuenciarobot instrobot 
            {
              Instruccion RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Secuenciacion(s, i); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("secuenciarobot",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // secuenciarobot ::= instrobot 
            {
              Instruccion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("secuenciarobot",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // instrobot ::= TkStore expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Almacenamiento(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // instrobot ::= TkCollect TkAs TkIdent TkPunto 
            {
              Instruccion RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String var = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Coleccion(new Identificador(var)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // instrobot ::= TkCollect TkPunto 
            {
              Instruccion RESULT =null;
		 RESULT = new Coleccion(null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // instrobot ::= TkDrop expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Soltado(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // instrobot ::= TkLeft expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Movimiento("left", e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // instrobot ::= TkRight expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Movimiento("right", e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // instrobot ::= TkUp expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Movimiento("up", e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // instrobot ::= TkDown TkPunto 
            {
              Instruccion RESULT =null;
		 RESULT = new Movimiento("down", null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // instrobot ::= TkLeft TkPunto 
            {
              Instruccion RESULT =null;
		 RESULT = new Movimiento("left", null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // instrobot ::= TkRight TkPunto 
            {
              Instruccion RESULT =null;
		 RESULT = new Movimiento("right", null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instrobot ::= TkUp TkPunto 
            {
              Instruccion RESULT =null;
		 RESULT = new Movimiento("up", null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instrobot ::= TkDown expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Movimiento("down", e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instrobot ::= TkRead TkPunto 
            {
              Instruccion RESULT =null;
		 RESULT = new Entrada(null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instrobot ::= TkRead TkAs TkIdent TkPunto 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Entrada(new Identificador(id)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instrobot ::= TkSend expr TkPunto 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Salida(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrobot",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr TkSuma expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinArit("+", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr TkResta expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinArit("-", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr TkMult expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinArit("*", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr TkDiv expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinArit("/", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr TkMod expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinArit("%", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= TkParAbre expr TkParCierra 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= TkResta expr 
            {
              Expresion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpUnaria("-", e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= TkNum 
            {
              Expresion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LiteralEntero(n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= TkIdent 
            {
              Expresion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Identificador(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= expr TkConjuncion expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinBool("/\\", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= expr TkDisyuncion expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinBool("\\/", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= TkNegacion expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpUnaria("~", e1); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= TkTrue 
            {
              Expresion RESULT =null;
		 RESULT = new LiteralBool(true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= TkFalse 
            {
              Expresion RESULT =null;
		 RESULT = new LiteralBool(false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr TkDesigual expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinRelacional("!=", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= expr TkIgual expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinRelacional("==", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= expr TkMayor expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinRelacional(">", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= expr TkMenor expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinRelacional("<", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= expr TkMayorIgual expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinRelacional(">=", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= expr TkMenorIgual expr 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ExpBinRelacional("<=", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= TkCaracter 
            {
              Expresion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LiteralCaracter(c); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
