
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int TkFalse = 55;
  public static final int TkSuma = 10;
  public static final int TkRight = 41;
  public static final int TkLeft = 37;
  public static final int TkNegacion = 23;
  public static final int TkTrue = 54;
  public static final int TkDeactivation = 49;
  public static final int TkComa = 18;
  public static final int TkDown = 36;
  public static final int TkDesigual = 32;
  public static final int TkOn = 29;
  public static final int TkCollect = 43;
  public static final int TkUp = 27;
  public static final int TkIf = 8;
  public static final int TkStore = 42;
  public static final int MENOS_UNARIO = 51;
  public static final int TkResta = 11;
  public static final int TkParAbre = 15;
  public static final int TkElse = 9;
  public static final int TkRead = 31;
  public static final int TkDefault = 44;
  public static final int TkAdvance = 45;
  public static final int TkInt = 5;
  public static final int TkDrop = 35;
  public static final int TkDeactivate = 47;
  public static final int TkIgual = 20;
  public static final int TkDosPuntos = 19;
  public static final int TkActivation = 48;
  public static final int TkConjuncion = 25;
  public static final int EOF = 0;
  public static final int TkSend = 38;
  public static final int TkDisyuncion = 24;
  public static final int error = 1;
  public static final int TkCreate = 2;
  public static final int TkDiv = 13;
  public static final int TkNum = 53;
  public static final int TkMenor = 21;
  public static final int TkMult = 12;
  public static final int TkAs = 26;
  public static final int TkChar = 30;
  public static final int TkIdent = 52;
  public static final int TkMenorIgual = 34;
  public static final int TkError = 50;
  public static final int TkParCierra = 16;
  public static final int TkMod = 14;
  public static final int TkMayor = 22;
  public static final int TkActivate = 46;
  public static final int TkExecute = 3;
  public static final int TkPunto = 17;
  public static final int TkMayorIgual = 33;
  public static final int TkBot = 6;
  public static final int TkCaracter = 39;
  public static final int TkWhile = 7;
  public static final int TkMe = 28;
  public static final int TkBool = 40;
  public static final int TkEnd = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TkCreate",
  "TkExecute",
  "TkEnd",
  "TkInt",
  "TkBot",
  "TkWhile",
  "TkIf",
  "TkElse",
  "TkSuma",
  "TkResta",
  "TkMult",
  "TkDiv",
  "TkMod",
  "TkParAbre",
  "TkParCierra",
  "TkPunto",
  "TkComa",
  "TkDosPuntos",
  "TkIgual",
  "TkMenor",
  "TkMayor",
  "TkNegacion",
  "TkDisyuncion",
  "TkConjuncion",
  "TkAs",
  "TkUp",
  "TkMe",
  "TkOn",
  "TkChar",
  "TkRead",
  "TkDesigual",
  "TkMayorIgual",
  "TkMenorIgual",
  "TkDrop",
  "TkDown",
  "TkLeft",
  "TkSend",
  "TkCaracter",
  "TkBool",
  "TkRight",
  "TkStore",
  "TkCollect",
  "TkDefault",
  "TkAdvance",
  "TkActivate",
  "TkDeactivate",
  "TkActivation",
  "TkDeactivation",
  "TkError",
  "MENOS_UNARIO",
  "TkIdent",
  "TkNum",
  "TkTrue",
  "TkFalse"
  };
}

